### ISSUE TITLE
PreTrained Weights

### ISSUE THREAD

**Issue by naveen27b** [faizan1234567/BraTS23-Tumors-Segmentation#4]
Hi Faizan, Thanks for making available this amazing work to everyone on github. I'm trying to use this model to obtain the brain tumor segmentation which I would be using for the downstream tasks. I currently have very limited computational resources to actually train the model and use it for inference. It would be really helpful if you could provide the pretrained model and its weights. I will make sure to give credits to this work if I use it for publication. thank you

**Comment by faizan1234567** [comment]
sure I will take it into the consideration.

**Comment by Navee402** [comment]
Hi, Thank you for your reply. I have one more question related to configurations. Can you elaborate a bit on  " --json_file JSON_FILE path to json file". If possible can you add it to the repository? Thank you
