### ISSUE TITLE
clarification regarding JSON File. " " --json_file JSON_FILE path to json file""

### ISSUE THREAD

**Issue by Navee402** [faizan1234567/BraTS23-Tumors-Segmentation#5]
Hi, Thank you for your reply. I have one more question related to configurations. Can you elaborate a bit on " --json_file JSON_FILE path to json file". What kind of data does it contain? Is it the folds data to train the model? If possible can you please add it to the repository for BraTS23 dataset? Thank you

**Comment by faizan1234567** [comment]
The json file contains paths to the training images. We use the json file to load images from a directory. It comes with the BraTS 23 dataset.

**Comment by faizan1234567** [comment]
It also have some folders information like 5 folds, and also it has information about paths of images and annotation like mask. I will add to the repository with a description.

**Comment by Navee402** [comment]
Hi, thanks once again for the reply but I am constantly getting runtime error whenever the validation step reaches. 'RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions." I have tried to run it in google colab as well as in my local computer with nvidia rtx3090. what could be the reason? any idea? thank you

**Comment by mirfan899** [comment]
json file still missing.
